model: smallcnn
dataset: SCDv1-10
load_clean_data: False
sample_rate: 16000
n_mfcc: 40
n_fft: 400
hop_length: 160
trigger_size: 5
poisoning_rate: 0.1
learning_rate: 0.0001
batch_size: 256
num_classes: 10
num_epoches: 300
patience: 20
result: badnets01